# Makefile generated by BNFC.

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Pi/Test

# Rules for building the parser.

Pi/ErrM.hs Pi/Lex.x Pi/Print.hs Pi/Par.y Pi/Test.hs : Pi.cf
	bnfc --haskell-gadt -d Pi.cf

%.hs : %.y
	happy --ghc --coerce --array --info $<

%.hs : %.x
	alex --ghc $<

Pi/Test : Pi/Test.hs Pi/ErrM.hs Pi/Lex.hs Pi/Par.hs Pi/Print.hs
	ghc --make $< -o $@

# Rules for cleaning generated files.

clean :
	-rm -f Pi/*.hi Pi/*.o Pi/*.log Pi/*.aux Pi/*.dvi

distclean : clean
	-rm -f Pi/Abs.hs Pi/Abs.hs.bak Pi/ComposOp.hs Pi/ComposOp.hs.bak Pi/Doc.txt Pi/Doc.txt.bak Pi/ErrM.hs Pi/ErrM.hs.bak Pi/Layout.hs Pi/Layout.hs.bak Pi/Lex.x Pi/Lex.x.bak Pi/Par.y Pi/Par.y.bak Pi/Print.hs Pi/Print.hs.bak Pi/SharedString.hs Pi/SharedString.hs.bak Pi/Skel.hs Pi/Skel.hs.bak Pi/Test.hs Pi/Test.hs.bak Pi/XML.hs Pi/XML.hs.bak Pi/AST.agda Pi/AST.agda.bak Pi/Parser.agda Pi/Parser.agda.bak Pi/IOLib.agda Pi/IOLib.agda.bak Pi/Main.agda Pi/Main.agda.bak Pi/Pi.dtd Pi/Pi.dtd.bak Pi/Test Pi/Lex.hs Pi/Par.hs Pi/Par.info Pi/ParData.hs Makefile
	-rmdir -p Pi/

# EOF
